#!/usr/bin/sh

# Get the timer from the user
ACTUAL_DATE=$(date +%s)
TIME="${1}"

print_help() {
  printf "Usage: \n# Focus 45 minutes\npomo 45m\n# Focus 1 hour\npomo 1h\n"
  exit 1
}

# Check if other pomodoro exists and if so exit
check_pomo() {
	for i in $(atq | awk '{print $1}');
	do
		if at -c "${i}" | grep -i pomo &>/dev/null; then
			notify-send "Pomo" "You already have a pomo until: $(atq "${i}" | awk '{print $5}')"
			exit 1
		fi
	done
}

# Convert m or h into minutes and hours
focus_time() {
	# Time to focus
  num="${1}"
	# Unit timer
	unit="${2}"

	case "${unit}" in
		"m")
			send_notification "${num}" "minutes"
			;;
		"h")
			send_notification "${num}" "hours"
			;;
		*)
			print_help
			;;
	esac
}

send_notification() {
	num="${1}"
	unit="${2}"
	# Set finish notification
	echo 'notify-send "Pomo" "Focus is over"' | at now + "${num}" "${unit}" &>/dev/null
	# Ugly one liner to get the expiration time
	timer_expire=$(atq $(atq | awk '{print $1}' \
	| parallel 'at -c {} | grep -i pomo &>/dev/null && echo {}') | awk '{print $5}')
	# Send init notification
	notify-send "Pomo" "Focus time until ${timer_expire}!"
}

# If no time specified by the user RTFM
if [[ -z "${TIME}" ]]; then
	print_help
fi

# Check existing pomodoro sessions
check_pomo

# Extract the number and unit
num="${TIME//[!0-9]/}"
unit="${TIME//[0-9]/}"

# Get the focus time and start the pomodoro
focus_time "${num}" "${unit}"
